# Generated by Django 5.1.3 on 2024-11-24 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherportal", "0005_attendance_remarks_alter_attendance_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teacherportal.teacher",
            ),
        ),
    ]
